### ISSUE TITLE
Compiler errors due to "TrueTy"/"FalseTy" structs in constants.h

### ISSUE THREAD

**Issue by gralkapk** [RenderKit/ospray#248]
These lines of code:

```C++
static struct TrueTy {
    __forceinline operator bool( ) const { return true; }
} True MAYBE_UNUSED;

static struct FalseTy {
    __forceinline operator bool( ) const { return false; }
} False MAYBE_UNUSED;
```

from <install_dir>/include/ospray/ospcommon/constants.h
cause compiler errors while compiling MegaMol.
I was using GCC v5.3.1.
MegaMol compiles with C++14 flag.

Commenting these lines out solves the problem, so far without causing any runtime issues.

Errors are:

![constants_compile_error](https://user-images.githubusercontent.com/27358560/39284017-822de0c8-48ce-11e8-86c2-70ef5cb1a81a.PNG)

**Comment by ingowald** [comment]
If the rest of ospray compiles through if those things get removed I
suggest we just axe them...

**Comment by gralkapk** [comment]
This issue still exists in 1.6

**Comment by Twinklebear** [comment]
@gralkapk can you test on the latest release-1.6 branch or devel and see if dc14ab4979d27a9099a1d5a64ae33fb16fbbbd6b has resolved the issue?

**Comment by gralkapk** [comment]
Yes. This issue is fixed with the current devel.

**Comment by Twinklebear** [comment]
👍 let's close this as well
