### ISSUE TITLE
Generating Lightmaps?

### ISSUE THREAD

**Issue by oschakravarthi** [RenderKit/ospray#318]
Hi
Thank you very much for the great effort.

I have a question. I request you to help. Sorry for asking my question as a "issue". I could not find any option in github to post a message to you.

I have been looking for a library which generates shadow map images (Image Based Lighting) for each mesh of my scene. (2nd UV channel). I mean, when we bake lighting of a scene in 3D editors like Blender/Maya/3ds max, it generates lightmap images which contain shadow information. I want to generate the same images programatically without using any such 3d editors. I have attached a a sample image to this post.
![9551170d15e201dad1c45266079ec43f8eaade55](https://user-images.githubusercontent.com/29388049/56785072-2a9a5180-6811-11e9-8239-26dbaf8a1613.jpeg)

Is it possible to achieve the same with OSPRay or Embree? If not possible, do you know any such library which is free/opensource?

I have seen many Path-Tracing/Ray-Tracing libraries but they all are rendering the complete scene without giving a clue how to generate those images. I have been struggling for more than 2 months.

Awaiting your reply.
Thanks in advance.

**Comment by johguenther** [comment]
Hi,
generating lightmaps is not supported yet with OSPRay, at least not out-of-the-box. It would be a new feature (we though about that before), however, not with high priority.

Maybe have a look at [Unity](https://unity3d.com/unity), it is free for non-professional use, and supports the generation of lightmaps.

Cheers,
  Johannes

**Comment by carsonbrownlee** [comment]
I am actually working on a prototype lightmapper using OSPRay, but this is currently strictly exploratory and not expected to be publicly released anytime soon if at all.  Johannes suggestion is a good one, as I know with Unity you can view and should be able to export generated lightmaps in the editor, if you can import your scene data into Unity.  Unreal may have similar functionality.

**Comment by oschakravarthi** [comment]
Thank you for your response. I cannot use unity for my requirement. I want to develop a service which does baking. So, when a 3d model is pushed to this service, it should bake it and export it and publish it to CDN. That is why I have been searching for such a library for more than 3 months. Not getting any clue.

**Comment by carsonbrownlee** [comment]
that sounds great and I'd love to hear how it progresses.  I'll try to remember to post to this issue if and when anything is released on our end.  It's pretty niche and generally built into game engines so I'm not too surprised you're not seeing many hits for a third party middleware.  you might try enlighten:  https://www.siliconstudio.co.jp/middleware/enlighten/en/ .  This is actually what Unity uses in its legacy lightmapper.

**Comment by oschakravarthi** [comment]
Thank you. But enlighten is not a free/open source solution. 😣On 30-Apr-2019 1:38 AM, carsonbrownlee <notifications@github.com> wrote:that sounds great and I'd love to hear how it progresses.  I'll try to remember to post to this issue if and when anything is released on our end.  It's pretty niche and generally built into game engines so I'm not too surprised you're not seeing many hits for a third party middleware.  you might try enlighten:  https://www.siliconstudio.co.jp/middleware/enlighten/en/ .  This is actually what Unity uses in its legacy lightmapper.

**Comment by LumiereDeLOmbre** [comment]
Hi,
Any news on this subject? thanks

**Comment by johguenther** [comment]
No, computing light maps is not planned anytime soon.

**Comment by johguenther** [comment]
See idea at https://github.com/ospray/ospray/issues/553#issuecomment-1432867926: would it be ok if the app/user needs to provide the geometry image (of the mesh to compute the light map for?
