### ISSUE TITLE
shadowCatcherPlane causes lighting artifacts 

### ISSUE THREAD

**Issue by mnaehrig** [RenderKit/ospray#524]
Pathtracing with shadowCatcherPlane enabled affects lighting in an unexpected way.

shadowCatcherPlane enabled (0, 0, 1, 0): 
![box_shadowcatcher](https://user-images.githubusercontent.com/13589110/168803064-a585e3b3-5ffe-49e9-a8bf-3fbbc1621ce3.jpg)

shadowCatcherPlane disabled:
![box_no_shadowcatcher](https://user-images.githubusercontent.com/13589110/168803991-819830cc-1206-4388-a17d-653c02850fff.jpg)

The scene contains just a single ambient light.

**Comment by johguenther** [comment]
I tried to reproduce the scene (simple geometry, single ambient light which is either visible, or using a background color), with current `devel`, looks good:
![scplane_on](https://user-images.githubusercontent.com/9035336/173792085-db48a9e4-18ef-4fab-a79c-7eefa2e64ab1.png)
![scplane_off](https://user-images.githubusercontent.com/9035336/173792094-88d05c16-11fe-4c01-979c-0432d92e4bb1.png)

Are there other (transparent?) objects in the scene?

**Comment by mnaehrig** [comment]
Hi Johannes,
many thanks for your support! There are no transparent objects in the scene. Also tried with current devel now, but the effect is still there. Finally I added a shadow plane option to ospExamples:

    static bool renderShadowPlane = false;
    if (ImGui::Checkbox("renderShadowPlane", &renderShadowPlane)) {
      if (renderShadowPlane) {
        renderer->setParam("shadowCatcherPlane", vec4f(0, 0, 1, 1));
        addObjectToCommit(renderer->handle());
      } else {
        renderer->setParam("shadowCatcherPlane", vec4f(0, 0, 0, 0));
        addObjectToCommit(renderer->handle());
      }
    }

With scene "planes" there is a noticable effect directly above the shadow plane:
![shadow_plane_on](https://user-images.githubusercontent.com/13589110/174954835-bf6fe478-52fb-474f-b295-2b665b6ea7c0.jpg)
![shadow_plane_off](https://user-images.githubusercontent.com/13589110/174954851-bcf72fbb-b208-451f-823d-e7c5f7694438.jpg)

**Comment by johguenther** [comment]
This is (finally) fixed in `devel` via f982427f7ef0b528b27a844b8f21906c34d44046 and a re-implementation of the Shadow Catcher, solving several issues. The commit also adds a plane coefficients widget to `ospExamples`, I checked that there are no illumination changes anymore with the `planes` test scene.
For best results it is advised when using the Shadow Catcher to take several samples per frame (via `lightSamples` and/or `pixelSamples`), say 16 or more, see also https://github.com/RenderKit/ospray#path-tracer.
