### ISSUE TITLE
[Feature request] Ground plane for Environment light

### ISSUE THREAD

**Issue by bharatshiyani** [RenderKit/ospray#569]
Hello, 

Can ground plane feature be implemented in ospray ? It is very useful for environment light, 

The example of it in THREE.JS
https://threejs.org/examples/?q=ground#webgl_materials_envmaps_groundprojected

![image](https://github.com/ospray/ospray/assets/26597849/a8b7eb11-bbfd-4c7f-8022-f29068d94aa8)

**Comment by johguenther** [comment]
Improvements and usage examples via f982427f7ef0b528b27a844b8f21906c34d44046.
