### ISSUE TITLE
Pseudo-color mapping on mesh surfaces

### ISSUE THREAD

**Issue by stukowski** [RenderKit/ospray#575]
I am wondering if there is a way to accomplish pseudo-color mapping for mesh surfaces with OSPRay? I need to visualize scalar quantities that are defined on a mesh's vertices.

The use of `OSPTransferFunction` is currently limited to 3d volumes.

The idea of using 2D textures to emulate pseudo-color mapping fails due to the out-of-bounds behavior for texture coordinates in OSPRay. There is no way to switch from the standard repeat mode to a clamp-to-edge mode, as is supported by OpenGL or ANARI samplers, for example. But maybe I overlooked something.

**Comment by johguenther** [comment]
Clamp2edge exists internally (used for the background texture), but is not yet exposed to be selectable via an texture parameter.

**Comment by stukowski** [comment]
It would be great if this UV wrap mode could be implemented for textures. This seems to be the missing piece to implement pseudo-color mapping with arbitrary color gradients for mesh, curve, and sphere geometries.
