### ISSUE TITLE
Backplate texture affected by pixel filter

### ISSUE THREAD

**Issue by stukowski** [RenderKit/ospray#590]
I am trying to render an image with a backplate texture to place some 2d graphics behind the 3d objects. I noticed that the background image gets blurred by the renderer's `pixelFilter`:

With `pixelFilter` set to `OSP_PIXELFILTER_GAUSS`:
![backplate_antialiased](https://github.com/user-attachments/assets/a5143682-49cf-4918-a738-f28efb09c93f)

With `pixelFilter` set to `OSP_PIXELFILTER_POINT`:
![backplate](https://github.com/user-attachments/assets/2a93a178-0a43-4c5c-8aa0-0968564f1f1d)

The backplate's resolution matches the framebuffer resolution and the texture filter is set to `OSP_TEXTURE_FILTER_NEAREST`. First, I thought the effect may be coming from the denoiser, but these pictures have been rendered without denoising filter.

Is there a way to leave the background image completely unaffected, but still get antialiasing of the rendered objects?

**Comment by johguenther** [comment]
What would currently work is to blend the backplate in the application (e.g. while displaying OSPRay's framebuffer), using the alpha-channel of the framebuffer (which contains the "opacity" of the rendered scene).
A fix in OSPRay could look like this, essentially always using the PixelFilter `POINT` for the backplate:
```diff
diff --git a/modules/cpu/render/pathtracer/PathTracer.ispc b/modules/cpu/render/pathtracer/PathTracer.ispc
index 98208fe58..d86240944 100644
--- a/modules/cpu/render/pathtracer/PathTracer.ispc
+++ b/modules/cpu/render/pathtracer/PathTracer.ispc
@@ -205,7 +205,7 @@ static ScreenSample PathTracer_renderPixel(PathTracer *uniform self,

     screenSample.ray.t = min(screenSample.ray.t, tMax);

-    pathContext.screen = cameraSample.screen;
+    pathContext.screen = cameraSample.pixel_center;
     ScreenSample sample = PathTraceIntegrator_Li(
         pathContext, pathState, screenSample.ray, screenSample.rayCone, ffh);
```

Yet, the backplate will still be denoised as well when the denoiser is active, which however should be fine for text.
We'll think about changing backplate handling, implementing it as a blend step as part of the postprocessing pipeline. Here the drawback is that colored transparency affecting the background won't work with monochrome alpha blending.

**Comment by stukowski** [comment]
Thanks a lot for the quick reply. Yes, it could be useful to have at least the option to exclude the background plate from the pixel filtering. That's what users of the `map_backplate` option want most of the time, I would guess.

I also considered doing the compositing in the application and not leaving it to the OSPRay renderer. However, this approach has its own pitfalls, which I was going to describe in a separate GitHub issue. Hope you don't mind if I hijack this thread now and describe two more related problems.

For one, the RGB components of the background color set on the renderer seem to always creep into the filtered pixels at the edges of an object, even if background alpha=0. The effect becomes quite pronounced when camera depth-of-field is used and the object edges are more blurry than usual:

<img width="453" alt="image" src="https://github.com/user-attachments/assets/d2f22dc4-1b99-47bf-9fd7-0cfa27ac8417">

The left picture rendered with the default `backgroundColor=(0,0,0,0)` looks good on a dark background, but on a light background the objects exhibit dark colors around their edges. So, my follow-up question would be, how can I render a picture with a transparent background such that it will look good when composited on *any* background, i.e., without knowing the background color a priori. In other words, I would like produce a rendering that can be saved as a PNG file and then placed on an arbitrary PowerPoint slide, for example. 

Maybe you have a better suggestion, but a possible solution I discovered is to reinterpret the framebuffer content of OSPRay as *premultipled alpha* (even though it is straight alpha, I think) after rendering the image with `backgroundColor=(0,0,0,0)`. For RGBA values with premultiplied alpha, [different rules](https://en.wikipedia.org/wiki/Alpha_compositing#Straight_versus_premultiplied) apply when combing the foreground image with the background. Here is how it looks like when treating the OSPRay framebuffer contents as premultiplied alpha:

<img width="213" alt="image" src="https://github.com/user-attachments/assets/a000b754-8f0c-4ca7-9e2c-b5f0ced03d66">
 

Another thing I noticed when rendering images with a transparent background (0,0,0,0) is that the alpha channel of the framebuffer contains stochastic noise in semi-transparent object regions. I am using the path tracer backend: 

<img width="321" alt="image" src="https://github.com/user-attachments/assets/9791e7c1-2638-4d66-b564-5a8826513a9c">

While the noise in the RGB channels is successfully eliminated by the denoising filter, the noise in the alpa channel remains. This leads to a problem when composing the semi-transparent image with a white background in the application. The noise reappears in the visible RGB channels (left) - unlike in the image directly rendered on a white background by OSPRay:

<img width="393" alt="image" src="https://github.com/user-attachments/assets/f81daaa8-61d8-4e14-abe1-ed3c70414576">

**Comment by johguenther** [comment]
Very elaborated post, thanks! I'll briefly comment
- a fix for the original issue will come soon (backplate to ignore the pixelFilter)
- yes, for compositing at the app side `backgroundColor` must be black+transparent and the correct blending mode be used (the documentation does not mention anything about pre-multiplied alpha, we should clarify that)
- commit 5b053439025b2857c60a8da7222045edb2cee9f7 added a parameter to denoise the alpha channel as well
- your last example also demonstrates the limitations of alpha-only blending I mentioned with respect to colored transparency: the brightness is different, because alpha is computed as a mix of the RGB transparency filter weights and thus cannot correctly regard the color of the background

**Comment by johguenther** [comment]
> the RGB components exceed the alpha component. This is not compatible with the pre-multiplied alpha interpretation

This is because alpha is computed as average of the "RGB opacity". Another view is that RGB is HDR and thus can be larger than 1.0.

**Comment by stukowski** [comment]
>> the RGB components exceed the alpha component. This is not compatible with the pre-multiplied alpha interpretation

> This is because alpha is computed as average of the "RGB opacity". Another view is that RGB is HDR and thus can be larger than 1.0.

Thanks for the explanation. Do you have a recommendation on how to clamp or normalize such color values for display or compositing? My observation is that a pre-multiplied alpha image in which the RGB components exceed alpha leads to “undefined behavior”, e.g. to unexpected colors of the affected pixels - depending on the software used to display the image. 

My current solution is:
```
R' = R * alpha / max(R,G,B,alpha)
G' = G * alpha / max(R,G,B,alpha)
B' = B * alpha / max(R,G,B,alpha)
```

**Comment by johguenther** [comment]
> depending on the software used to display the image

If blending works in HDR (exceeding 1.0 is fine) then no adjustments are needed. Otherwise, your approach to renormalize the colors is reasonable (just exclude the alpha==0 case).

**Comment by stukowski** [comment]
> When I apply the pre-multiplied alpha scheme, they appear lighter (but still noisy due to the missing alpha channel denoising)

Here the same image rendered with OSPRay 3.2.0, alpha channel denoising, and highest-quality mode  - (looks a lot better, thanks!):

![image](https://github.com/user-attachments/assets/56c3507b-80e5-4396-89ba-5834f3a8c165)
