### ISSUE TITLE
Ospray v3, Windows 10 installation, pb locating ospray_studio.exe 

### ISSUE THREAD

**Issue by mdpxa** [RenderKit/ospray#595]
hello Windows Ospray users,
I am a Freecad user, I installed Ospray on my Windows 10 PC using [ospray-3.2.0.x86_64.windows.msi](https://github.com/ospray/OSPRay/releases/download/v3.2.0/ospray-3.2.0.x86_64.windows.msi) 
This is to produce renderings for Freecad developments.
Freecad knows Ospray and needs to be told where the executable is installed.
Please see below the bin directory that the Intel installer created:

![Ospray installer result](https://github.com/user-attachments/assets/7183b79f-d037-440f-9e85-95429b778fc3)

If anyone knows which file in it is the renderer executable Freecad is needing (Freecad doens't document this detail), please let me know.
Or if there are more details I should provide.
Many thanks,

**Comment by johguenther** [comment]
It looks like FreeCAD uses the OSPRay *Studio* application to import the data via files, thus you need to get `ospStudio.exe` by installing [ospray_studio-1.1.0.x86_64.windows.msi](https://github.com/RenderKit/ospray-studio/releases/download/v1.1.0/ospray_studio-1.1.0.x86_64.windows.msi).

**Comment by mdpxa** [comment]
I spent a long time looking for ospray_stuio.exe and never noticed the ospstudio in the directory. :-(
Thank you very much!

**Comment by BruceCherniak** [comment]
Hello. I am the maintainer of OSPRay Studio and can offer some assistance.

Upon seeing your issue, I reached out to @howetuft, the maintainer of the FreeCAD-render workbench repo (https://github.com/FreeCAD/FreeCAD-render).  Their recommendation is to take a look at the install instructions here https://github.com/FreeCAD/FreeCAD-render/blob/master/docs/EngineInstall.md#ospray-studio-1
