### ISSUE TITLE
Point lights and ring lights seem to not work under scivis renderer mode?

### ISSUE THREAD

**Issue by meerkatpapa** [RenderKit/ospray#596]
In my experiments, I can visualize scene objects with point lights/ring lights using ao renderer, but the same scene turns to black when I change the renderer to scivis or pathtracer renderer. Is this a known issue or did I do anything wrong?

**Comment by johguenther** [comment]
The `ao` renderer ignores all lightsources and just computes an (implicit) ambient illumination. So if `scivis` or `pathtracer` remain black the light sources likely point into the wrong direction or are too dim. To debug
- set a bright background color (let's you see at the silhouettes of objects)
- temporarily add an `ambient` light (`scivis` or `pathtracer` need that explicitly)

**Comment by meerkatpapa** [comment]
@johguenther Thank you for your quick reply.

I am a bit confused by what you said "scivis or pathtracer need an ambient light explicitly". It sounds like "For scivis and pathtracer renderers, explicitly adding an ambient light to the scene is necessity for users to trigger the full functionality of a point light". Am I correct?

**Comment by johguenther** [comment]
Ah, no: scivis and pathtracer do *not* need an ambient light for the point light to work. However, adding the ambient light  is needed to have a similar illumination which the ao renderer computes. I suggested this just for debugging purposes only: to be able to see something in the scene and to navigate. Once the point light is setup correctly you can remove the ambient light.
E.g., it can also be that the point light is stuck somewhere inside of an object.
